### ISSUE TITLE
Columnt Layout broken

### ISSUE THREAD

**Issue by maitikeisi** [jeffjose/redditpx#17]
Hi,

I noticed that the Column Layout has been broken since the fullscreen button got added to the code.
Seems like ColumnLayout.svelte file is missing the togglefullscreen function.
https://github.com/jeffjose/redditpx/commit/6c6c318423fcc84c0414ebb37d8fbb6a6a08b38e#comments

**Comment by jeffjose** [comment]
ha. This is embarrassing. Thanks for reporting. Let me take a look.
