### ISSUE TITLE
Typo in URL "open reddit" extra /

### ISSUE THREAD

**Issue by terraqueem** [jeffjose/redditpx#31]
Both Shortcuts open an new Tab with an extra /

```
https://www.reddit.com//r/itookapicture/.....
```
Happens with both Keybindings (r, o).
And both opens the old Reddit Page regardless the settings.

**Comment by jeffjose** [comment]
Is that causing an issue or just something you noticed?

**Comment by terraqueem** [comment]
> 
I would expect that it opens the corresponding reddit page e.g. old or new reddit.
But it could also be that Reddit resolve this URL wrongly.

**Comment by terraqueem** [comment]
I dont know how to debug svelte, but i looked at the code.

Could the / be redundant here?

https://github.com/jeffjose/redditpx/blob/master/src/routes/home.svelte?plain=1#L108-L109
https://github.com/jeffjose/redditpx/blob/master/src/components/FullscreenLayout.svelte?plain=1#L683
https://github.com/jeffjose/redditpx/blob/master/src/_utils.ts?plain=1#L451
https://github.com/jeffjose/redditpx/blob/master/src/routes/randnsfw.svelte?plain=1#L9
https://github.com/jeffjose/redditpx/blob/master/src/routes/random.svelte?plain=1#L9

Or can you tell me where the functions for the r + o keybindings are defined.

**Comment by maitikeisi** [comment]
If it's keybindings r and o causing the issue then the correct line would be
https://github.com/jeffjose/redditpx/blob/master/src/components/FullscreenLayout.svelte?plain=1#L691
(keys get defined here: https://github.com/jeffjose/redditpx/blob/master/src/components/FullscreenLayout.svelte?plain=1#L839)
and the function one below that. Same lines can be found in ColumnsLayout too, different position of course.

Slash before the variable looks to be redundant as the permalink fetched from json starts with a / and most likely causes the double slash when using the keybinding. 
json permalink example
"permalink": "/r/funny/comments/uq9pjw/going_forward_comics_may_only_be_posted_on/"

In my testing the extra slash didn't cause any issues tho. (o key opened the old.reddit and r key opened the regular one without issues).

**Comment by terraqueem** [comment]
@maitikeisi thanks for adding to this.
The issue im experiencing is, that with both keybindings it opens the old reddit design.
My thought was that reddit interprets the typo in the URI and falls back to the old page design.

https://old.reddit.com//r/wallpapers/comments/yv5s5r/high_revs_4200x2363/

https://www.reddit.com//r/wallpapers/comments/yvn3dr/motel_along_route_66_tucumcari_new_mexico_usa/

**Comment by jeffjose** [comment]
Fixed. Changes now live at https://stage.redditpx.com/r/pics 

I'll push the changes to redditpx.com (production) in a few days.

**Comment by jeffjose** [comment]
Fixed.
